### ISSUE TITLE
Creating new group causing '405 HTTP method not allowed'

### ISSUE THREAD

**Issue by ivanmilov** [phiresky/timetrackrs#13]
Hello again :)

I am trying to create a new test group:
![image](https://user-images.githubusercontent.com/522518/150550400-0f0adb5b-a8f2-4581-acf9-a41758f3c736.png)

When I click on "Save changes" and reload the page the new group disappears.
Console output:
![image](https://user-images.githubusercontent.com/522518/150550604-04aea23a-272d-4d56-a6ba-1eb0fc6a7c46.png)

**Comment by phiresky** [comment]
Yeah, the rule editor is broken right now sadly - it needs some changes (probably minor) to get the base functionality working since I changed some internal stuff around. at the least the HTTP request path changed to update-rule-groups but there might be something else that needs to be changed. 
![image](https://user-images.githubusercontent.com/2303841/150551065-942fc16a-8d3d-45ed-b37f-4fd15e7d98c8.png)


also the extracted cache needs to probably be invalidated completely when the rules change

**Comment by phiresky** [comment]
even then, the rule editor is really clunky right now and i'm not sure if it even has all the right buttons to be feature complete :)

**Comment by ivanmilov** [comment]
hmm, it makes the tool hardly usable. I wanted to create a set of rules to see how long I am working during the day.
Currently 'arbtt' works well, but timetrackrs looks better and, in theory, provides more flexebility

**Comment by phiresky** [comment]
yeah, i know - the rule editor worked before at least in a basic way, but i've also been manually editing the config for my own use. it'll probably be fixed in the next few days

**Comment by ivanmilov** [comment]
ok, waiting for fixes :)
